spring.application.name=pt-restful-hibernate
logging.level.org.springframework=info
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
#mysql
spring.datasource.url=jdbc:mysql://localhost:3307/springptdb
spring.datasource.username=springpt
spring.datasource.password=springptpw

#auto 속성 
#create - 기존 테이블 삭제 후 다시 생성(DROP + CREATE) 
#create-drop - create와 같으나 종료시점에 테이블 DROP
#update - 변경분만 반영. 
#validate - 엔티티와 테이블이 정상 매핑되었는지만 확인. 
#none - 사용x 관리상 none 또는 주석처리. 

#운영시 create, create-drop, update 사용하면 안됨. 
#개발 서버는 update 또는 validate. 
#스테이징과 운영 서버는 validate 또는 none. 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.security.user.name=syuk27 #=> jwt 사용을 위해 주석 
#spring.security.user.password=1234

server.port=9090
