spring.application.name=pt-restful-hibernate
logging.level.org.springframework=info
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
#mysql
spring.datasource.url=jdbc:mysql://localhost:3307/springptdb
spring.datasource.username=springpt
spring.datasource.password=springptpw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.security.user.name=syuk27 #=> jwt 사용을 위해 주석 
#spring.security.user.password=1234

server.port=9090
